import "./globals.css";

import { SpeedInsights } from "@vercel/speed-insights/next";

import NavBar from "./components/layout/Header/NavBar";
import Footer from "./components/layout/Footer/Footer";

import { bentonLight, bentonReg, centralNoLight, centralNoReg } from "./fonts";

export const metadata = {
  title: "Sabal House",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={` ${bentonLight.variable}
        ${bentonReg.variable}
        ${centralNoLight.variable}
        ${centralNoReg.variable}h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {children}
        <Footer />
        <SpeedInsights />
      </body>
    </html>
  );
}
